package com.jawa.app

/** The 16 moon phase drawables (generated by tools/gen_icons.py), picked by [Moon.iconIndex]. */
object MoonIcons {
    private val ICONS = intArrayOf(
        R.drawable.moon_00, R.drawable.moon_01, R.drawable.moon_02, R.drawable.moon_03,
        R.drawable.moon_04, R.drawable.moon_05, R.drawable.moon_06, R.drawable.moon_07,
        R.drawable.moon_08, R.drawable.moon_09, R.drawable.moon_10, R.drawable.moon_11,
        R.drawable.moon_12, R.drawable.moon_13, R.drawable.moon_14, R.drawable.moon_15,
    )

    fun forAge(age: Double): Int = ICONS[Moon.iconIndex(age)]
}
