#!/usr/bin/env python3
"""Generates the weather icon vector drawables (and an SVG preview sheet).

Each icon is described once as a list of shapes; the script writes it both as
an Android <vector> drawable and as SVG, so the preview matches the app.
Run from the repo root:  python3 tools/gen_icons.py
"""
import os, sys

SUN = "#FFC53D"
MOON = "#F4EBC1"
CLOUD = "#F1F4F8"
CLOUD_DARK = "#AEB8C6"
CLOUD_BACK = "#C5CDD8"
RAIN = "#4FB3FF"
SNOW = "#FFFFFF"
BOLT = "#FFD43B"
FOG = "#C9D1DB"


def circle(cx, cy, r):
    return f"M{cx - r},{cy} a{r},{r} 0 1,0 {2 * r},0 a{r},{r} 0 1,0 {-2 * r},0 Z"


# shape = ("fill", color, path) or ("stroke", color, width, path)
def cloud(color):
    return [("fill", color, circle(20, 38, 10)), ("fill", color, circle(32, 28, 13)),
            ("fill", color, circle(45, 38, 10)), ("fill", color, "M20,34 H45 V48 H20 Z")]


def sun():
    rays = ("M32,5 L32,12 M32,52 L32,59 M5,32 L12,32 M52,32 L59,32 "
            "M12.9,12.9 L17.9,17.9 M46.1,46.1 L51.1,51.1 M12.9,51.1 L17.9,46.1 M46.1,17.9 L51.1,12.9")
    return [("stroke", SUN, 4, rays), ("fill", SUN, circle(32, 32, 12))]


def moon():
    return [("fill", MOON, "M40,10 A22,22 0 1,0 54,44 A20,20 0 0,1 40,10 Z")]


def stars():
    return [("fill", MOON, circle(56, 15, 1.8)), ("fill", MOON, circle(49, 25, 1.3))]


def group(shapes, tx=0, ty=0, s=1):
    return ("group", tx, ty, s, shapes)


def lines(color, width, d):
    return [("stroke", color, width, d)]


def flakes(points):
    d = ""
    for x, y in points:
        d += (f"M{x - 3.2},{y} H{x + 3.2} M{x - 1.6},{y - 2.8} L{x + 1.6},{y + 2.8} "
              f"M{x - 1.6},{y + 2.8} L{x + 1.6},{y - 2.8} ")
    return [("stroke", SNOW, 1.8, d.strip())]


UP = dict(tx=5, ty=-4, s=0.85)  # cloud lifted up to make room for rain/snow

ICONS = {
    "wx_clear_day": sun(),
    "wx_clear_night": moon() + stars(),
    "wx_partly_day": [group(sun(), 0, 0, 0.62), group(cloud(CLOUD), 9, 14, 0.85)],
    "wx_partly_night": [group(moon(), 0, 0, 0.62), group(cloud(CLOUD), 9, 14, 0.85)],
    "wx_cloudy": [group(cloud(CLOUD), 0, 1, 1)],
    "wx_overcast": [group(cloud(CLOUD_BACK), 18, 0, 0.7), group(cloud(CLOUD), 1, 12, 0.9)],
    "wx_fog": [group(cloud(CLOUD), **UP)] + lines(FOG, 3.5, "M10,45 H40 M22,53 H54 M14,60 H44"),
    "wx_drizzle": [group(cloud(CLOUD), **UP)] + lines(
        RAIN, 3, "M22,45 L21,49 M32,48 L31,52 M42,45 L41,49 M27,56 L26,60 M37,56 L36,60"),
    "wx_rain": [group(cloud(CLOUD), **UP)] + lines(
        RAIN, 3.5, "M20,44 L17,52 M31,44 L28,52 M42,44 L39,52 M25,55 L22,62 M36,55 L33,62"),
    "wx_showers_day": [group(sun(), 0, 0, 0.5), group(cloud(CLOUD), 9, 3, 0.8)] + lines(
        RAIN, 3.5, "M25,47 L22,55 M36,47 L33,55 M47,47 L44,55"),
    "wx_snow": [group(cloud(CLOUD), **UP)] + flakes([(21, 47), (33, 47), (45, 47), (27, 57), (39, 57)]),
    "wx_thunder": [group(cloud(CLOUD_DARK), **UP),
                   ("fill", BOLT, "M34,35 L24,50 H31 L27,62 L40,45 H33 L38,35 Z")] + lines(
        RAIN, 3, "M18,44 L16,50 M47,44 L45,50"),
}


def android_shapes(shapes, indent="    "):
    out = []
    for sh in shapes:
        if sh[0] == "group":
            _, tx, ty, s, inner = sh
            out.append(f'{indent}<group android:translateX="{tx}" android:translateY="{ty}" '
                       f'android:scaleX="{s}" android:scaleY="{s}">')
            out += android_shapes(inner, indent + "    ")
            out.append(f"{indent}</group>")
        elif sh[0] == "fill":
            out.append(f'{indent}<path android:fillColor="{sh[1]}" android:pathData="{sh[2]}" />')
        else:
            out.append(f'{indent}<path android:strokeColor="{sh[1]}" android:strokeWidth="{sh[2]}" '
                       f'android:strokeLineCap="round" android:strokeLineJoin="round" '
                       f'android:pathData="{sh[3]}" />')
    return out


def svg_shapes(shapes):
    out = []
    for sh in shapes:
        if sh[0] == "group":
            _, tx, ty, s, inner = sh
            out.append(f'<g transform="translate({tx},{ty}) scale({s})">' + "".join(svg_shapes(inner)) + "</g>")
        elif sh[0] == "fill":
            out.append(f'<path fill="{sh[1]}" d="{sh[2]}"/>')
        else:
            out.append(f'<path fill="none" stroke="{sh[1]}" stroke-width="{sh[2]}" '
                       f'stroke-linecap="round" stroke-linejoin="round" d="{sh[3]}"/>')
    return out


def vector_xml(shapes, size_dp=64, viewport=64):
    body = "\n".join(android_shapes(shapes))
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by tools/gen_icons.py -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size_dp}dp" android:height="{size_dp}dp"\n'
            f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">\n{body}\n</vector>\n')


def svg(shapes):
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">' + "".join(svg_shapes(shapes)) + "</svg>"


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    draw = os.path.join(root, "app/src/main/res/drawable")
    for name, shapes in ICONS.items():
        with open(os.path.join(draw, name + ".xml"), "w") as f:
            f.write(vector_xml(shapes))
    # Launcher icon foreground: partly-sunny icon centred in the 108dp adaptive canvas
    fg = [group(ICONS["wx_partly_day"], 22, 22, 1)]
    with open(os.path.join(draw, "ic_launcher_foreground.xml"), "w") as f:
        f.write(vector_xml(fg, 108, 108))
    if len(sys.argv) > 1:  # optional: write SVGs for previewing
        os.makedirs(sys.argv[1], exist_ok=True)
        for name, shapes in ICONS.items():
            with open(os.path.join(sys.argv[1], name + ".svg"), "w") as f:
                f.write(svg(shapes))
    print("wrote", len(ICONS), "icons")
