#!/usr/bin/env python3
"""Generates res/layout/widget_weather.xml (repetitive slot views). Run from repo root."""
import os

def slot(prefix, i):
    return f'''
        <LinearLayout
            android:id="@+id/{prefix}_slot_{i}"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="center_horizontal"
            android:orientation="vertical">
            <TextView
                android:id="@+id/{prefix}_label_{i}"
                style="@style/WidgetSmall"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" />
            <ImageView
                android:id="@+id/{prefix}_icon_{i}"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:layout_marginTop="2dp"
                android:layout_marginBottom="1dp"
                android:importantForAccessibility="no"
                android:src="@drawable/wx_cloudy" />
            <TextView
                android:id="@+id/{prefix}_temp_{i}"
                style="@style/WidgetValue"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" />
        </LinearLayout>'''

def row(rid, prefix, n):
    return f'''
    <LinearLayout
        android:id="@+id/{rid}"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="6dp"
        android:orientation="horizontal">{"".join(slot(prefix, i) for i in range(n))}
    </LinearLayout>
'''

xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_widget_layout.py.
     Header, then the next days (hidden only if the widget is 1 row tall). -->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/widget_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/widget_bg"
    android:orientation="vertical"
    android:paddingStart="16dp"
    android:paddingTop="12dp"
    android:paddingEnd="16dp"
    android:paddingBottom="10dp">

    <!-- Header takes all the height the days row doesn't need. The temperature on the
         left sizes itself to fill it, whatever size the launcher gives the widget. -->
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:minHeight="64dp"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/current_temp"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:autoSizeMaxTextSize="160sp"
            android:autoSizeMinTextSize="40sp"
            android:autoSizeStepGranularity="2sp"
            android:autoSizeTextType="uniform"
            android:fontFamily="sans-serif-light"
            android:gravity="start|center_vertical"
            android:includeFontPadding="false"
            android:maxLines="1"
            android:text="--°"
            android:textColor="@color/widget_text" />

        <!-- Right: weather icon above place, description, today's high / low -->
        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_marginStart="8dp"
            android:gravity="end|center_vertical"
            android:orientation="vertical">

            <ImageView
                android:id="@+id/current_icon"
                android:layout_width="wrap_content"
                android:layout_height="0dp"
                android:layout_gravity="end"
                android:layout_marginBottom="4dp"
                android:layout_weight="1"
                android:adjustViewBounds="true"
                android:importantForAccessibility="no"
                android:maxWidth="96dp"
                android:maxHeight="96dp"
                android:scaleType="fitEnd"
                android:src="@drawable/wx_partly_day" />

            <TextView
                android:id="@+id/place"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="end"
                android:ellipsize="end"
                android:maxWidth="150dp"
                android:maxLines="1"
                android:text="@string/widget_name"
                android:textColor="@color/widget_text"
                android:textSize="15sp"
                android:textStyle="bold" />

            <TextView
                android:id="@+id/description"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="end"
                android:ellipsize="end"
                android:maxWidth="150dp"
                android:maxLines="1"
                android:text="Tap to load"
                android:textColor="@color/widget_text_dim"
                android:textSize="14sp" />

            <TextView
                android:id="@+id/details"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="end"
                android:maxLines="1"
                android:textColor="@color/widget_text_faint"
                android:textSize="14sp" />
        </LinearLayout>
    </LinearLayout>
{row("days_row", "day", 5)}
    <!-- ‹  ━ • •  › : switch between saved places (hidden with only one place) -->
    <LinearLayout
        android:id="@+id/nav_row"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="4dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">
        <TextView
            android:id="@+id/prev"
            style="@style/WidgetArrow"
            android:text="‹" />
        <TextView
            android:id="@+id/dots"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="center"
            android:includeFontPadding="false"
            android:maxLines="1"
            android:textColor="@color/widget_text"
            android:textSize="9sp" />
        <TextView
            android:id="@+id/next"
            style="@style/WidgetArrow"
            android:text="›" />
    </LinearLayout>
</LinearLayout>
'''
# Static preview shown in the launcher's widget list (Android 12+): sample data.
def preview_day(label, icon, hi, lo):
    return f'''
        <LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1"
            android:gravity="center_horizontal" android:orientation="vertical">
            <TextView style="@style/WidgetSmall" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="{label}" />
            <ImageView android:layout_width="30dp" android:layout_height="30dp" android:layout_marginTop="2dp"
                android:layout_marginBottom="1dp" android:importantForAccessibility="no" android:src="@drawable/{icon}" />
            <TextView style="@style/WidgetValue" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="{hi}° {lo}°" />
        </LinearLayout>'''

preview = xml.split("<LinearLayout\n        android:id=\"@+id/days_row\"")[0]
preview = preview.replace('android:id="@+id/', 'android:tag="')  # no ids needed in a preview
preview = (preview.replace('android:text="--°"', 'android:text="14°"')
           .replace('android:text="@string/widget_name"', 'android:text="Nepomuk"')
           .replace('android:text="Tap to load"', 'android:text="Partly cloudy"')
           .replace('android:textColor="@color/widget_text_faint"', 'android:text="18° / 9°"\n                android:textColor="@color/widget_text_faint"'))
days = [("Today", "wx_showers_day", 18, 9), ("Fri", "wx_rain", 15, 8), ("Sat", "wx_overcast", 14, 7), ("Sun", "wx_partly_day", 17, 6), ("Mon", "wx_clear_day", 19, 7)]
preview += f'''<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="6dp"
        android:orientation="horizontal">{"".join(preview_day(*d) for d in days)}
    </LinearLayout>
</LinearLayout>
'''
preview = preview.replace("Generated by tools/gen_widget_layout.py.", "Generated by tools/gen_widget_layout.py: widget-list preview.")

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
open(os.path.join(root, "app/src/main/res/layout/widget_weather.xml"), "w").write(xml)
open(os.path.join(root, "app/src/main/res/layout/widget_preview.xml"), "w").write(preview)
print("ok")
